apiVersion: v1
kind: Namespace
metadata:
  name: kubedns
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kubed
  namespace: kubedns
spec:
  interval: 1m
  url: https://charts.appscode.com/stable/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubed
  namespace: kubedns
spec:
  releaseName: kubed
  chart:
    spec:
      chart: kubed
      sourceRef:
        kind: HelmRepository
        name: kubed
        namespace: kubedns
      version: v0.13.2
  interval: 1m
